goodsProductTool:
  component: "@sls-next/serverless-component@latest"
  inputs:
    roleArn: "arn:aws:iam::020329126309:role/serverlessRole"
    bucketName: "duckzill-discord-s3"
    name:
      defaultLambda: "duckzillDiscordLambda"
      apiLambda: "duckzillDiscordApiLambda"
      imageLambda: "duckzillDiscordImageLambda"